### ISSUE TITLE
Add PAW download

### ISSUE THREAD

**Issue by Gidgidonihah** [CruxConnect/crux-api-docs#59]
It would be nice to have the PAW file available for everyone to use and download.

**Comment by Gidgidonihah** [comment]
Even better to have postman format with variables and all that.

Even best to have both.

**Comment by Gidgidonihah** [comment]
Also we need to have the .paw files committed to the repo for central storage.

**Comment by Gidgidonihah** [comment]
See the `mock-paw-download` branch for boilerplate to link to a download.

**Comment by baileymatthewr** [comment]
This issue was closed with PR #70
